### PR TITLE
Support UnionAll methods

### LINKED ISSUE #49: Can't make `Base.show` extensible:
MWE: 
```julia
using ExtensibleUnions
struct MyUnion end
extensibleunion!(MyUnion)

struct Foo end
addtounion!(MyUnion, Foo)

Base.show(io::IO, x::MyUnion) = print(io, "boo!")

extensiblefunction!(show, MyUnion)
```
this throws:
```julia
julia> extensiblefunction!(show, MyUnion)
ERROR: type UnionAll has no field types
Stacktrace:
 [1] getproperty at ./Base.jl:15 [inlined]
 [2] _replace_types(::Type{Tuple{typeof(show),IO,MIME{Symbol("text/plain")},T} where T<:AbstractChar}) at /Users/mason/.julia/packages/ExtensibleUnions/4cHBq/src/update_methods.jl:122
 [3] _update_single_method!(::Function, ::Type{#s13} where #s13<:Tuple, ::Set) at /Users/mason/.julia/packages/ExtensibleUnions/4cHBq/src/update_methods.jl:44
 [4] _update_all_methods_for_extensiblefunction!(::Any) at /Users/mason/.julia/packages/ExtensibleUnions/4cHBq/src/update_methods.jl:21
 [5] extensiblefunction!(::Function, ::Tuple) at /Users/mason/.julia/packages/ExtensibleUnions/4cHBq/src/extensible_functions.jl:23
 [6] extensiblefunction!(::Function, ::Type) at /Users/mason/.julia/packages/ExtensibleUnions/4cHBq/src/extensible_functions.jl:2
 [7] top-level scope at REPL[14]:1
```

### PR DESCRIPTION
**Pull request by MasonProtter**
Closes #49 and #18.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
That was fast! :)

**Comment by DilumAluthge** [comment]
bors merge

**Comment by MasonProtter** [comment]
I think its the inlining that reduced coverage there, I'm pretty sure the tests I added hit those methods...

**Comment by DilumAluthge** [comment]
Can you modify .travis.yml to disable inlining for the tests? Basically you’ll have to specify the script.

**Comment by MasonProtter** [comment]
Okay I think I turned off inlining correctly but I'm not sure.

**Comment by DilumAluthge** [comment]
So I actually don’t think that will be enough. The after_script part isn’t the issue, it’s the script itself.

The default Julia script is: https://docs.travis-ci.com/user/languages/julia/#default-build-and-test-script

So we need to add a script section containing the default script except with inlining disabled.

**Comment by DilumAluthge** [comment]
bors merge

**Comment by DilumAluthge** [comment]
Alright, so things did get better when we disabled inlining. The coverage of the file `src/update_methods.jl` went from 95.70% (inlining enabled) to 96.77% (inlining disabled). But it looks like some methods still aren't getting hit.

Maybe add some unit tests specifically for those methods that CodeCov says aren't getting hit?

**Comment by DilumAluthge** [comment]
bors merge

**Pull request merged**
